gizmo_home:
    path:     /
    defaults: { _controller: controller.page:homeAction }

gizmo_article_page:
    path:     /articles/{category}/{title}
    defaults: { _controller: controller.page:pageAction , category:null, title:null }

gizmo_all_page:
    path:     /all/{category}/{title}
    defaults: { _controller: controller.page:pageAction , title:null}

project_view:
    path: /project/{code}/{name2}
    defaults: { _controller: controller.project:viewAction}

project_update:
    path: /project/update
    defaults: { _controller: controller.project:updateAction }
    
project_infinite_scroll:
    path: /project/search
    defaults: { _controller: controller.project:infiniteProjectsScrollAction }

contact_us:
        path: /contact
        defaults: { _controller: controller.contact:contactAction }
contact_thankyou:
        path: /thankyou/{from_page}
        defaults: { _controller: controller.contact:thankyouAction }
login:
    path: /auth/login
    defaults: { _controller: controller.auth:loginAction }

login_check:
    path: /administration/login-check

lab_logout:
    path: /auth/logout



#api secured

api_secured_load_project:
    path: /api/secured/project/get/{code}
    defaults: { _controller: controller.api_project:viewJsonAction }

api_secured_load_slides:
    path: /api/secured/project/get-slides/{code}
    defaults: { _controller: controller.api_project:viewSlidesJsonAction }

api_secured_add_slide:
    path: /api/secured/project/add-slide/{code}
    defaults: { _controller: controller.api_project:addSlideAction }
    methods: [POST]

api_secured_published_status:
     path: /api/secured/project/sync/{code}
     defaults: { _controller: controller.api_project:syncAction }
     methods: [POST]

api_secured_add_avatar:
     path: /api/secured/project/add-avatar/{code}
     defaults: { _controller: controller.api_project:addAvatarAction }
     methods: [POST]

#administration secured

administration_project_index:
    path: /administration/project/index
    defaults: { _controller: controller.admin_project:indexAction }

administration_project_remove:
    path: /administration/project/remove/{id}
    defaults: { _controller: controller.admin_project:removeAction }
    methods:  [POST]

administration_project_inline_edit:
    path: /administration/project/edit-inline/{id}
    defaults: { _controller: controller.admin_project:inlineEditAction }

administration_project_edit:
    path: /administration/project/edit/{code}
    defaults: { _controller: controller.admin_project:editAction }


administration_user_index:
    path: /administration/user/index
    defaults: { _controller: controller.admin_user:indexAction }

administration_user_remove:
    path: /administration/user/remove/{id}
    defaults: { _controller: controller.admin_user:removeAction }
    methods:  [POST]

administration_user_edit:
    path: /administration/user/edit/{id}
    defaults: { _controller: controller.admin_user:editAction }