services:

#event listener services
    listener.response_created:
        class: Gizmo\GizmoBundle\Event\ControllerListener
        arguments: [@templating,@manager.content,@=service('doctrine.orm.default_entity_manager').getRepository('GizmoBundle:Project')]
        tags:
             - { name: kernel.event_listener, event: kernel.response, method: preExecute }

#manager services
    manager.content:
        class: Gizmo\GizmoBundle\Service\ContentManager
        arguments: [@templating, @api_caller,"%cms_api_url%"]

    manager.project:
        class: Gizmo\GizmoBundle\Service\ProjectManager
        arguments: [@doctrine.orm.entity_manager]

    manager.user:
        class: Gizmo\GizmoBundle\Service\UserManager
        arguments: [@doctrine.orm.entity_manager,@security.encoder_factory,@event_dispatcher]

#controller services
    controller.page:
        class: Gizmo\GizmoBundle\Controller\PageController
        arguments: [@templating,@router]

    controller.contact:
        class: Gizmo\GizmoBundle\Controller\ContactController
        arguments: [@templating,@router,@mailer]

    controller.project:
        class: Gizmo\GizmoBundle\Controller\ProjectController
        arguments: [@templating,@=service('doctrine.orm.default_entity_manager').getRepository('GizmoBundle:Project'),@router,@knp_paginator,@doctrine.orm.entity_manager]

    controller.auth:
        class: Gizmo\GizmoBundle\Controller\AuthController
        arguments: [@templating,@router]

    #api secured controller services
    controller.api_project:
        class: Gizmo\GizmoBundle\Controller\Api\ProjectController
        arguments: [@manager.project,@manager.user,@form.factory]


    #admin controller services
    controller.admin_project:
        class: Gizmo\GizmoBundle\Controller\Administration\ProjectController
        arguments: [@templating,@form.factory,@=service('doctrine.orm.default_entity_manager').getRepository('GizmoBundle:Project'),@=service('doctrine.orm.default_entity_manager').getRepository('GizmoBundle:User'),@manager.project,@router,@validator]

    controller.admin_user:
        class: Gizmo\GizmoBundle\Controller\Administration\UserController
        arguments: [@templating,@form.factory,@manager.user,@=service('doctrine.orm.default_entity_manager').getRepository('GizmoBundle:User'),@router]
        
    app.twig_extension:
        class: Gizmo\GizmoBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
